services:
  #redis:
  #  image: "redis:8.0-M03-alpine"
  #  ports:
  #    - 6379:6379
  #  command: redis-server
  #  volumes:
  #    - ./db/redis:/data
  valkey:
    image: "valkey/valkey:8.0.2-alpine"
    ports:
      - 6379:6379
    command: valkey-server 
    volumes:
      - ./db/valkey:/data
  postgresql:
    image: "postgres:17.2-alpine3.21"
    container_name: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: kadou
    volumes:
      - ./db/postgresql:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080